### ISSUE TITLE
How to use ember-concurrency-retryable with the decorators provided by ember-concurrency?

### ISSUE THREAD

**Issue by JenLyndle** [maxfierke/ember-concurrency-retryable#422]
Thanks a lot for this wonderful addon! I am in process of upgrading my code to the latest version of Ember and ember-concurrency. For Eg., Am changing the tasks from:

`setupTask: task(function * () {}).drop()`

to:

`@dropTask *setupTask() { };`

How does this work in case of retryable tasks? Any pointers on how to migrate the following code to be compliant with the latest Ember concurrency will be much appreciated!
```
fooTask : retryable(task(function * () {
   .....
}).drop().evented(), retryPolicy);
```

**Comment by maxfierke** [comment]
Fairly sure we worked this out on Discord back in June, but for posterity (so I can close this out), the way to implement this combination using decorators, would be:

```javascript
@task({ drop: true, evented: true, retryable: retryPolicy })
*fooTask() {
  // ...
}
```
