### ISSUE TITLE
Decorator?

### ISSUE THREAD

**Issue by lougreenwood** [maxfierke/ember-concurrency-retryable#5]
Any thoughts/plans on adding a decorator for the add-on?

for reference, here are ember-concurrency decorators: https://github.com/machty/ember-concurrency-decorators

**Comment by maxfierke** [comment]
@lougreenwood I'd love to support a decorator! I'm not using decorators anywhere right now, so I'd have to spend some time to look into them. I would happily accept a PR, if someone who's deep into decorators figures one out before I do!

**Comment by lougreenwood** [comment]
Cool, I may give it a shot over the weekend :)

**Comment by lougreenwood** [comment]
Seems that this is actually covered by `ember-concurrency-decorators` 🎉 

```
  @dropTask({ retryable: someBackoffPolicy })
  *fooTask () {
    // task logic...
  }
```


* usage example: https://github.com/machty/ember-concurrency-decorators/issues/17
* https://github.com/machty/ember-concurrency-decorators/pull/26

**Comment by allthesignals** [comment]
@lougreenwood how'd you get this to work? ember-concurrency-decorators is not liking my `retryable` property
